
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stub-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stub-node
  template:
    metadata:
      labels:
        app: stub-node
    spec:
      nodeSelector:
        kubernetes.io/hostname: debian
      containers:
        - name: stub-node
          image: leonardogonmac/stub-node:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: raspberry
      containers:
        - name: game-server
          image: leonardogonmac/service-a-python:rpi
          imagePullPolicy: Always
          ports:
            - containerPort: 50051 # gRPC
            - containerPort: 8001  # Prometheus Metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-server
  template:
    metadata:
      labels:
        app: validation-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: vaio
      containers:
        - name: validation-server
          image: leonardogonmac/service-b-python:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
            - containerPort: 8002
